### ISSUE TITLE
Falta archivo de código

### ISSUE THREAD

**Issue by mancpato** [Luis-D-UABCS/SerieFibonacci#1]
El código no va en el README, ahí van comentarios en lenguaje natural sobre el proyecto

**Comment by Luis-D-UABCS** [comment]
Una disculpa, es mi primera vez utilizando está plataforma...

A lo que leí, tengo que crear una sucursal dentro del repositorio y es ahí
donde va el código?

**Comment by mancpato** [comment]
Espero que todo haya quedado más claro. Si sigues con dudas, pregunta por
Discord.

"La ciencia no es perfecta, pero es la mejor herramienta para entender el
mundo."

Prof. Miguel Ángel Norzagaray Cosío
Departamento de Sistemas Computacionales
Universidad Autónoma de BCS

-- 






















 PRIVACIDAD DE ESTE MENSAJE

La información
contenida 
en esta comunicación es enviada únicamente para el uso de la persona
o 
entidad a quien está dirigida y de cualquier otra persona que esté 
expresamente
autorizada para recibirla. Puede contener información 
confidencial o legalmente
privilegiada. Si Usted no es el destinatario, 
queda en este acto notificado
que, en caso de cualquier divulgación, 
reproducción, distribución o cualquier
acción con relación al contenido de 
esta información, se encuentra
estrictamente prohibido y podría ser sujeto 
de un proceso legal. Los derechos
de privacidad y confidencialidad de la 
información en este mensaje no se
pierden por el hecho de haberse 
trasmitido erróneamente o por causas de
interferencias en el funcionamiento 
de los sistemas de correo y canales de comunicación.
Toda opinión que se 
expresa en este mensaje pertenece a la persona remitente,
por lo que no 
debe entenderse necesariamente como una opinión de la Universidad
Autónoma 
de B.C.S. Así mismo no se hace responsable si los mensajes llegan con

demora, incompletos, eliminados o con algún programa malicioso denominado 
como
virus informático, lo anterior tomando en consideración de que los 
mensajes
enviados de manera electrónica pueden ser interceptados y 
manipulados.  Si Usted ha recibido esta comunicación por
error, por favor 
notifíquenoslo inmediatamente respondiendo a este correo
electrónico y 
después bórrelo de su sistema junto con cualquier documento
adjunto que 
pudiera contener.
